Dockerfile, requirements-test.txt
=> 🐋 Docker tests

chowda/config.py, chowda/db.py, tests/locustfile.py
Expanded locust tests to include `/create` routes with factories
=> 🏋 Load testing

.github/workflows/CI.yml, .gitignore, chowda/models.py, pdm.lock, pyproject.toml, tests/factories.py, tests/test_factories.py
Adds [factory_boy](https://factoryboy.readthedocs.io/en/stable/) models with relational data
Adds factory tests
=> 👲 `factory_boy`: relational data

.github/workflows/update.yml
> On Wednesdays, we update our dependencies.
- Adds [update dependencies workflow](https://github.com/WGBH-MLA/.github/blob/main/.github/workflows/update.yml)
- Runs every Wednesday at 8a ET
- Uses [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request)
- Updates PR if there's already a previous PR
=> 👚 Update workflow

.gitignore, chowda/__init__.py, chowda/db.py, chowda/models.py, chowda/views.py, pdm.toml, pyproject.toml, tests/factories.py, tests/locustfile.py, tests/seeds.py, tests/test_factories.py
- Removes ruff ignores
- Fixes lint errors
=> ✋ Unignore ruff rules

docs/install.md, main.py
- Fixes doc typo 
- Removes old main.py
=> 🖊  Fix Doc Typo

.coveragerc, pyproject.toml, tests/seeds.py, tests/test_factories.py
Fixes coverage reports
- Adds `__init__.py` to make coverage reports work
- Moves `.coveragerc` options to `pyproject.toml`
=> 🛌 Fixes Coverage

.github/workflows/CI.yml, .vscode/launch.json, chowda/__init__.py, docs/examples/session.ipynb, pdm.lock, pyproject.toml, tests/test_app.py
- Tests notebooks with nbmake
- Adds `--nbmake` to CI tests
- Adds `docs` to pytest `testpaths`
=> 📓 Notebook tests

chowda/models.py
Displays ClamsApp name in select boxes
=> 📛 ClamsApp name

chowda/app.py, chowda/views.py
Adds column labeled 'Size' for the count of related MediaFile objects.
=> Updates Collection and Batch list view

.github/workflows/CI.yml, chowda/views.py
Updates github ref for `pytest` workflow from `pdm` -> `main`
=> ☝️ Updates workflow pointer

.github/workflows/docs.yml
Updates github ref in docs.yml workflow to use 'main' branch.
=> 👉 Updates docs workflow pointer

.github/workflows/CD.yml, .github/workflows/CI.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .github/workflows/update.yml
Adds `on: workflow_dispatch` to all actions, to allow manual running.
=> 🎖 workflow_dispatch

chowda/views.py, templates/forms/media_files.html
Create a batch from a list of guids
- `<textarea>` to paste list of guids
- Match to guids in db
- Return list of errors
- Add error guids to frontend
Closes #56
=> 🗒 Batch input from text

.vscode/launch.json, chowda/__init__.py, chowda/config.py, chowda/views.py, pdm.lock, pyproject.toml, templates/dashboard.html
Adds widget to display list of recent sync events
Closes #85
Closes #87
=> 🔄 Displays sync history in dashboard

chowda/views.py
Includes mmif_json in detail view
- Hides from list view
Allows viewing mmif results from WGBH-MLA/mario#4
Fixes batches list view bug - Closes #97
=> 🌄 `mmif_json` view

chowda/routers/dashboard.py, chowda/views.py
Uses session for flash and error messages
Closes #95
=> 📸 Uses session for flash and error messages

templates/forms/media_files.html
Use tabler class for textarea form fields
Fixes whitespace issues by using `{%-  ... -%}` jinja brackets
Closes #99
=> 🏓 Batch: tabler class

chowda/auth/utils.py, chowda/routers/dashboard.py, chowda/utils.py, chowda/views.py, static/js/custom_render.js, templates/displays/media_file_count.html, templates/displays/media_files.html, templates/forms/media_files.html
Adds custom Batch action for `Start`
- Only available to `user.is_clammer`
Closes #55
- Moves `UserToken` and auth functions to `chowda.auth.utils`
- Adds `@property` for `user.is_admin` and `user.is_clammer`
- Fixes `media_file_count` issues
=> Adds action 'Start' to Batches

chowda/views.py, templates/displays/media_file_count.html
Adds display template for media file count
=> 🔢 `media_file_count`

chowda/views.py
Adds base auth permission for all views
- All can read
- Clammers can `C-UD`
- Visible to Clammers and Admins
- Admins can `C-UD`
Closes #112
=> 🔐 Auth permissions

chowda/utils.py, chowda/views.py, pdm.lock, pyproject.toml, templates/forms/media_files.html, tests/test_batches.py
- Fixes #114 
- Adds documentation to validation steps
- Improves form display
=> 114 fix batch save

chowda/views.py
Duplicates batches
Merges MediFiles into new batch
=> Adds 'Duplicate' and 'Combine' actions for Batches.

templates/displays/batch_media_files.html, templates/displays/collection_media_files.html
Fixes `media_file` links to point to actual MediaFiles
Closes #126
=> 🔗 Fixes `media_file` links

chowda/views.py
Adds actions for `create_batch` and `create_multiple_batches` from Collections
- Merges all collections into a single new batch
- Create a batch for each selected Collection
Closes #131
=> 🧑‍🍳️ Create Batch from Collection

chowda/fields.py, chowda/views.py
Default sort by Batch.id, descending order
Moved custom fields to `fields.py`
Closes #129
=> ⬇️ Batch default sort

chowda/fields.py, chowda/routers/events.py, chowda/views.py, static/js/custom-render.js, templates/displays/finished.html, templates/displays/successful.html
Adds custom bool fields for Finished, Successful
- `True` Blue check ✔️  
- `False` Grey clock 🕐
- `True` Green circle check ✅ 
- `False` Red circle X ❌
Closes #183
=> 🎱 Fields: `Finished`, `Successful`

chowda/fields.py, chowda/views.py, static/js/custom-render.js, templates/displays/batch_metaflow_runs.html, templates/displays/metaflow_link_field.html, templates/displays/metaflow_pathspec_link_field.html
Adds Metaflow link fields for `MetaflowRun`:
- `pathspec`
- `current_step`
- `current_task`
Includes display templates, and custom render keys
=> ⛓️ Metaflow links

Dockerfile
Activates virtual environment in production image
=> 🦸 Activate production venv

Dockerfile
Adds `venv` directory to start of `$PATH`
=> 🏞 venv `PATH`

Dockerfile
Adds `pip` to virtual environment to fix production pipeline issues.
=> 📦 Adds pip to venv

Dockerfile, chowda/fields.py
Installs pip into `.venv` `python` to fix metaflow runs
=> 🍼 Ensure pip

docs/examples/Argo.ipynb, docs/index.md, docs/install.md, docs/reference/database.md, docs/reference/deploy.md, docs/reference/index.md, pyproject.toml
=> 📓 Update Docs
